### ISSUE TITLE
PyDelphin is missing its license

### ISSUE THREAD

**Issue by goodmami** [draplater/hrg-parser#1]
Hi,

I'm happy that PyDelphin was able to help with your project, but I must ask that you include the [LICENSE](https://github.com/delph-in/pydelphin/blob/develop/LICENSE) file. The MIT license is very permissive and doesn't constrain what you do with or how you license your own work, but it does state that the license and copyright notice (which is included in the LICENSE file) must be included with all "substantial portions" of the software. It should be fine to just copy the LICENSE file into the delphin/ subdirectory.

Cheers,

**Comment by draplater** [comment]
Fixed in d012fef. Thanks!

**Comment by goodmami** [comment]
Thank you!
